/*
 * robohash/manifest.js — GENERATED by scripts/build-robohash-parts.py.
 * Do not edit by hand; re-run the script instead.
 *
 * The pinned index -> file mapping for the vendored Robohash parts. A
 * genome stores one index per slot, so this ordering must never change:
 * a saved individual (its PTO trace, embedded in an exported PNG) would
 * otherwise decode to a different creature.
 *
 * Slots are in PASTE (z) order. `bbox` is the part's alpha bounding box
 * normalised to 0..1, used as the pivot when a part is scaled/rotated.
 *
 * A plain <script> assigning a global rather than JSON + fetch(), so the
 * app still works when index.html is opened over file://, where fetch()
 * of a local file is blocked.
 */
window.ROBOHASH_MANIFEST = {
 "version": 1,
 "sets": {
  "set4": {
   "label": "Cats",
   "artist": "David Revoy",
   "artistUrl": "https://www.peppercarrot.com/extras/html/2016_cat-generator/",
   "license": "CC-BY-4.0",
   "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
   "size": 384,
   "dir": "img/robohash/set4",
   "upstream": "https://github.com/e1ven/Robohash (sets/set4)",
   "slots": [
    {
     "name": "body",
     "srcDir": "000#00body",
     "parts": [
      {
       "file": "00.webp",
       "src": "000#body0.png",
       "bbox": [
        0.0449,
        0.0029,
        1.0,
        1.0
       ]
      },
      {
       "file": "01.webp",
       "src": "001#body1.png",
       "bbox": [
        0.0283,
        0.0137,
        0.9824,
        1.0
       ]
      },
      {
       "file": "02.webp",
       "src": "002#body2.png",
       "bbox": [
        0.0303,
        0.0176,
        0.9902,
        1.0
       ]
      },
      {
       "file": "03.webp",
       "src": "003#body3.png",
       "bbox": [
        0.0479,
        0.0195,
        0.9717,
        1.0
       ]
      },
      {
       "file": "04.webp",
       "src": "004#body4.png",
       "bbox": [
        0.041,
        0.0049,
        0.9717,
        1.0
       ]
      },
      {
       "file": "05.webp",
       "src": "005#body5.png",
       "bbox": [
        0.0479,
        0.0029,
        0.9668,
        1.0
       ]
      },
      {
       "file": "06.webp",
       "src": "006#body6.png",
       "bbox": [
        0.0361,
        0.0176,
        0.9727,
        1.0
       ]
      },
      {
       "file": "07.webp",
       "src": "007#body7.png",
       "bbox": [
        0.0479,
        0.0029,
        0.9805,
        1.0
       ]
      },
      {
       "file": "08.webp",
       "src": "008#body8.png",
       "bbox": [
        0.0479,
        0.0029,
        0.9668,
        1.0
       ]
      },
      {
       "file": "09.webp",
       "src": "009#body9.png",
       "bbox": [
        0.0293,
        0.0,
        0.9941,
        1.0
       ]
      },
      {
       "file": "10.webp",
       "src": "010#body10.png",
       "bbox": [
        0.04,
        0.0098,
        0.9736,
        1.0
       ]
      },
      {
       "file": "11.webp",
       "src": "011#body11.png",
       "bbox": [
        0.04,
        0.0176,
        0.9766,
        1.0
       ]
      },
      {
       "file": "12.webp",
       "src": "012#body12.png",
       "bbox": [
        0.0283,
        0.0537,
        0.9639,
        1.0
       ]
      },
      {
       "file": "13.webp",
       "src": "013#body13.png",
       "bbox": [
        0.0479,
        0.0195,
        0.9668,
        1.0
       ]
      },
      {
       "file": "14.webp",
       "src": "014#body14.png",
       "bbox": [
        0.0479,
        0.0195,
        0.9668,
        1.0
       ]
      }
     ]
    },
    {
     "name": "fur",
     "srcDir": "001#01fur",
     "parts": [
      {
       "file": "00.webp",
       "src": "000#fur0.png",
       "bbox": [
        0.0654,
        0.1367,
        0.9424,
        0.9756
       ]
      },
      {
       "file": "01.webp",
       "src": "001#fur1.png",
       "bbox": [
        0.0449,
        0.1055,
        0.9277,
        0.9639
       ]
      },
      {
       "file": "02.webp",
       "src": "002#fur2.png",
       "bbox": null
      },
      {
       "file": "03.webp",
       "src": "003#fur3.png",
       "bbox": [
        0.0557,
        0.1162,
        0.9561,
        0.9727
       ]
      },
      {
       "file": "04.webp",
       "src": "004#fur4.png",
       "bbox": [
        0.0947,
        0.1318,
        0.8613,
        1.0
       ]
      },
      {
       "file": "05.webp",
       "src": "005#fur5.png",
       "bbox": [
        0.0957,
        0.1328,
        0.8613,
        1.0
       ]
      },
      {
       "file": "06.webp",
       "src": "006#fur6.png",
       "bbox": null
      },
      {
       "file": "07.webp",
       "src": "007#fur7.png",
       "bbox": [
        0.1309,
        0.041,
        0.8467,
        1.0
       ]
      },
      {
       "file": "08.webp",
       "src": "008#fur8.png",
       "bbox": [
        0.0625,
        0.1455,
        0.9424,
        0.9082
       ]
      },
      {
       "file": "09.webp",
       "src": "009#fur9.png",
       "bbox": [
        0.082,
        0.1074,
        0.9141,
        0.9941
       ]
      }
     ]
    },
    {
     "name": "eyes",
     "srcDir": "002#02eyes",
     "parts": [
      {
       "file": "00.webp",
       "src": "000#eyes0.png",
       "bbox": [
        0.5303,
        0.2891,
        0.916,
        0.5371
       ]
      },
      {
       "file": "01.webp",
       "src": "001#eyes1.png",
       "bbox": [
        0.5195,
        0.3701,
        0.9258,
        0.5098
       ]
      },
      {
       "file": "02.webp",
       "src": "002#eyes2.png",
       "bbox": [
        0.624,
        0.4033,
        0.8672,
        0.4678
       ]
      },
      {
       "file": "03.webp",
       "src": "003#eyes3.png",
       "bbox": [
        0.5469,
        0.2539,
        0.9326,
        0.499
       ]
      },
      {
       "file": "04.webp",
       "src": "004#eyes4.png",
       "bbox": [
        0.4395,
        0.2656,
        0.8613,
        0.7744
       ]
      },
      {
       "file": "05.webp",
       "src": "005#eyes5.png",
       "bbox": [
        0.5635,
        0.3213,
        0.9014,
        0.5068
       ]
      },
      {
       "file": "06.webp",
       "src": "006#eyes6.png",
       "bbox": [
        0.5723,
        0.418,
        0.9033,
        0.4893
       ]
      },
      {
       "file": "07.webp",
       "src": "007#eyes7.png",
       "bbox": [
        0.5176,
        0.2842,
        0.9229,
        0.5225
       ]
      },
      {
       "file": "08.webp",
       "src": "008#eyes8.png",
       "bbox": [
        0.5518,
        0.3379,
        0.9121,
        0.5088
       ]
      },
      {
       "file": "09.webp",
       "src": "009#eyes9.png",
       "bbox": [
        0.5537,
        0.2988,
        0.9209,
        0.5186
       ]
      },
      {
       "file": "10.webp",
       "src": "010#eyes10.png",
       "bbox": [
        0.457,
        0.292,
        0.9629,
        0.4805
       ]
      },
      {
       "file": "11.webp",
       "src": "011#eyes11.png",
       "bbox": [
        0.5752,
        0.2988,
        0.8828,
        0.4922
       ]
      },
      {
       "file": "12.webp",
       "src": "012#eyes12.png",
       "bbox": [
        0.3213,
        0.3213,
        0.9844,
        0.5156
       ]
      },
      {
       "file": "13.webp",
       "src": "013#eyes13.png",
       "bbox": [
        0.5791,
        0.2676,
        0.8887,
        0.4717
       ]
      },
      {
       "file": "14.webp",
       "src": "014#eyes14.png",
       "bbox": [
        0.4785,
        0.293,
        0.9443,
        0.4844
       ]
      }
     ]
    },
    {
     "name": "mouth",
     "srcDir": "003#03mouth",
     "parts": [
      {
       "file": "00.webp",
       "src": "000#mouth0.png",
       "bbox": [
        0.7031,
        0.54,
        0.835,
        0.6504
       ]
      },
      {
       "file": "01.webp",
       "src": "001#mouth1.png",
       "bbox": [
        0.6582,
        0.5312,
        0.8867,
        0.6221
       ]
      },
      {
       "file": "02.webp",
       "src": "002#mouth2.png",
       "bbox": [
        0.751,
        0.5654,
        0.7949,
        0.6309
       ]
      },
      {
       "file": "03.webp",
       "src": "003#mouth3.png",
       "bbox": [
        0.627,
        0.5264,
        0.8564,
        0.6729
       ]
      },
      {
       "file": "04.webp",
       "src": "004#mouth4.png",
       "bbox": [
        0.6855,
        0.5273,
        0.8389,
        0.6484
       ]
      },
      {
       "file": "05.webp",
       "src": "005#mouth5.png",
       "bbox": [
        0.6855,
        0.5264,
        0.8389,
        0.6484
       ]
      },
      {
       "file": "06.webp",
       "src": "006#mouth6.png",
       "bbox": [
        0.6836,
        0.541,
        0.8545,
        0.6152
       ]
      },
      {
       "file": "07.webp",
       "src": "007#mouth7.png",
       "bbox": [
        0.7324,
        0.5381,
        0.8291,
        0.6523
       ]
      },
      {
       "file": "08.webp",
       "src": "008#mouth8.png",
       "bbox": [
        0.6279,
        0.54,
        0.834,
        0.6426
       ]
      },
      {
       "file": "09.webp",
       "src": "009#mouth9.png",
       "bbox": [
        0.6777,
        0.543,
        0.833,
        0.666
       ]
      }
     ]
    },
    {
     "name": "accessories",
     "srcDir": "004#04accessories",
     "parts": [
      {
       "file": "00.webp",
       "src": "000#accessory0.png",
       "bbox": [
        0.2725,
        0.5117,
        0.9844,
        0.9502
       ]
      },
      {
       "file": "01.webp",
       "src": "001#accessory1.png",
       "bbox": [
        0.4688,
        0.6533,
        0.7646,
        0.7939
       ]
      },
      {
       "file": "02.webp",
       "src": "002#accessory2.png",
       "bbox": [
        0.457,
        0.6523,
        0.7373,
        0.7383
       ]
      },
      {
       "file": "03.webp",
       "src": "003#accessory3.png",
       "bbox": [
        0.2598,
        0.1406,
        0.9297,
        0.7627
       ]
      },
      {
       "file": "04.webp",
       "src": "004#accessory4.png",
       "bbox": [
        0.5059,
        0.0615,
        0.8408,
        0.2832
       ]
      },
      {
       "file": "05.webp",
       "src": "005#accessory5.png",
       "bbox": [
        0.2324,
        0.0,
        0.6309,
        0.376
       ]
      },
      {
       "file": "06.webp",
       "src": "006#accessory6.png",
       "bbox": [
        0.2773,
        0.0146,
        0.9541,
        1.0
       ]
      },
      {
       "file": "07.webp",
       "src": "007#accessory7.png",
       "bbox": [
        0.2812,
        0.5117,
        0.9551,
        0.9502
       ]
      },
      {
       "file": "08.webp",
       "src": "008#accessory8.png",
       "bbox": [
        0.4688,
        0.6523,
        0.8057,
        0.8379
       ]
      },
      {
       "file": "09.webp",
       "src": "009#accessory9.png",
       "bbox": [
        0.6289,
        0.6582,
        1.0,
        1.0
       ]
      },
      {
       "file": "10.webp",
       "src": "010#accessory10.png",
       "bbox": [
        0.4541,
        0.6553,
        0.7441,
        0.8369
       ]
      },
      {
       "file": "11.webp",
       "src": "011#accessory11.png",
       "bbox": [
        0.2588,
        0.0,
        0.9297,
        0.7627
       ]
      },
      {
       "file": "12.webp",
       "src": "012#accessory12.png",
       "bbox": [
        0.5059,
        0.0615,
        0.8408,
        0.2832
       ]
      },
      {
       "file": "13.webp",
       "src": "013#accessory13.png",
       "bbox": [
        0.2578,
        0.002,
        0.6182,
        0.3311
       ]
      },
      {
       "file": "14.webp",
       "src": "014#accessory14.png",
       "bbox": [
        0.2734,
        0.0264,
        0.9502,
        0.9375
       ]
      },
      {
       "file": "15.webp",
       "src": "015#accessory15.png",
       "bbox": null
      }
     ]
    }
   ]
  }
 }
};
